### ISSUE TITLE
errors with scipy 1.5

### ISSUE THREAD

**Issue by ntessore** [skypyproject/skypy#198]
The new scipy 1.5 release contains some internal changes that break SkyPy code. This is a from a test run:

```console
$ tox -e test-scipy15
...
Package versions:
Numpy: 1.19.0
Scipy: 1.5.0
Matplotlib: not available
h5py: not available
Pandas: not available
astropy-helpers: 4.0.1
...
=================================== FAILURES ===================================
___________ [doctest] skypy.galaxy.ellipticity.beta_ellipticity_gen ____________
054     .. [1] Kacprzak T., Herbel J., Nicola A. et al., arXiv:1906.01018
055
056     Examples
057     --------
058     >>> from skypy.galaxy.ellipticity import beta_ellipticity
059
060     Sample 10 random variates from the Kacprzak model with
061     :math:`e_{\rm ratio} = 0.5` and :math:`e_{\rm sum} = 1.0`:
062
063     >>> ellipticity = beta_ellipticity.rvs(0.5, 1.0, size=10)
UNEXPECTED EXCEPTION: AttributeError("'NoneType' object has no attribute 'beta'")
Traceback (most recent call last):
  File "lib/python3.7/doctest.py", line 1330, in __run
    compileflags, 1), test.globs)
  File "<doctest skypy.galaxy.ellipticity.beta_ellipticity_gen[1]>", line 1, in <module>
  File ".tox/test-scipy15/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 1002, in rvs
    vals = self._rvs(*args)
  File ".tox/test-scipy15/lib/python3.7/site-packages/skypy/galaxy/ellipticity.py", line 21, in reparameterize
    return beta_method(self, *beta_args, a, b)
  File ".tox/test-scipy15/lib/python3.7/site-packages/skypy/galaxy/ellipticity.py", line 75, in _rvs
    return super()._rvs(*args)
  File ".tox/test-scipy15/lib/python3.7/site-packages/scipy/stats/_continuous_distns.py", line 588, in _rvs
    return random_state.beta(a, b, size)
AttributeError: 'NoneType' object has no attribute 'beta'
.tox/test-scipy15/lib/python3.7/site-packages/skypy/galaxy/ellipticity.py:63: UnexpectedException
____________________________ test_beta_ellipticity _____________________________

    def test_beta_ellipticity():

        from skypy.galaxy.ellipticity import beta_ellipticity

        # Initialise a randomised ellipticity distribution, an equivalent beta
        # distribution and special cases where the ellipticity distribution is
        # equivalent to a uniform distribution and an arcsine distribution.
        a, b = np.random.lognormal(size=2)
        args = (a / (a + b), a + b)
        beta_dist = stats.beta(a, b)
        ellipticity_dist = beta_ellipticity(*args)
        ellipticity_uniform = beta_ellipticity(0.5, 2.0)
        ellipticity_arcsine = beta_ellipticity(0.5, 1.0)

        # Range of input values spanning the support of the distributions
        x = np.linspace(0, 1, 100)

        # Check basic properties of distribution implementation
        check_normalization(beta_ellipticity, args, 'beta_ellipticity')
        check_edge_support(beta_ellipticity, args)
>       check_random_state_property(beta_ellipticity, args)

../../.tox/test-scipy15/lib/python3.7/site-packages/skypy/galaxy/tests/test_ellipticity.py:30:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../.tox/test-scipy15/lib/python3.7/site-packages/scipy/stats/tests/common_tests.py:190: in check_random_state_property
    r0 = distfn.rvs(*args, size=8)
../../.tox/test-scipy15/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:1002: in rvs
    vals = self._rvs(*args)
../../.tox/test-scipy15/lib/python3.7/site-packages/skypy/galaxy/ellipticity.py:21: in reparameterize
    return beta_method(self, *beta_args, a, b)
../../.tox/test-scipy15/lib/python3.7/site-packages/skypy/galaxy/ellipticity.py:75: in _rvs
    return super()._rvs(*args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <skypy.galaxy.ellipticity.beta_ellipticity_gen object at 0x116ed4610>
a = 0.4156994866391866, b = 0.6146797013294975, size = None, random_state = None

    def _rvs(self, a, b, size=None, random_state=None):
>       return random_state.beta(a, b, size)
E       AttributeError: 'NoneType' object has no attribute 'beta'

../../.tox/test-scipy15/lib/python3.7/site-packages/scipy/stats/_continuous_distns.py:588: AttributeError
_________________________________ test_ryden04 _________________________________

    def test_ryden04():
        from skypy.galaxy.ellipticity import ryden04

        # sample a single ellipticity
        e = ryden04(0.222, 0.056, -1.85, 0.89)
>       assert np.isscalar(e)
E       assert False
E        +  where False = <function isscalar at 0x1134575f0>(array([0.66569798]))
E        +    where <function isscalar at 0x1134575f0> = np.isscalar

../../.tox/test-scipy15/lib/python3.7/site-packages/skypy/galaxy/tests/test_ellipticity.py:86: AssertionError
=============================== warnings summary ===============================
.tox/test-scipy15/lib/python3.7/importlib/_bootstrap.py:219: 26 tests with warnings
  .tox/test-scipy15/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
    return f(*args, **kwds)

.tox/test-scipy15/lib/python3.7/site-packages/skypy/galaxy/ellipticity.py::skypy.galaxy.ellipticity.beta_ellipticity_gen
  .tox/test-scipy15/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:998: VisibleDeprecationWarning: The signature of <bound method _ellipticity_parameterization.<locals>.reparameterize of <skypy.galaxy.ellipticity.beta_ellipticity_gen object at 0x116ed4610>> does not contain a "size" keyword.  Such signatures are deprecated.
    np.VisibleDeprecationWarning)

.tox/test-scipy15/lib/python3.7/site-packages/skypy/galaxy/redshift.py::skypy.galaxy.redshift.smail_gen
  .tox/test-scipy15/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:998: VisibleDeprecationWarning: The signature of <bound method smail_gen._rvs of <skypy.galaxy.redshift.smail_gen object at 0x11f220d50>> does not contain a "size" keyword.  Such signatures are deprecated.
    np.VisibleDeprecationWarning)

.tox/test-scipy15/lib/python3.7/site-packages/skypy/galaxy/redshift.py::skypy.galaxy.redshift.smail_gen
  .tox/test-scipy15/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:998: VisibleDeprecationWarning: The signature of <bound method smail_gen._rvs of <skypy.galaxy.redshift.smail_gen object at 0x1206ea650>> does not contain a "size" keyword.  Such signatures are deprecated.
    np.VisibleDeprecationWarning)

.tox/test-scipy15/lib/python3.7/site-packages/skypy/galaxy/tests/test_redshift.py::test_smail
  .tox/test-scipy15/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:998: VisibleDeprecationWarning: The signature of <bound method smail_gen._rvs of <skypy.galaxy.redshift.smail_gen object at 0x116eb4c10>> does not contain a "size" keyword.  Such signatures are deprecated.
    np.VisibleDeprecationWarning)

.tox/test-scipy15/lib/python3.7/site-packages/skypy/galaxy/tests/test_redshift.py::test_smail
  .tox/test-scipy15/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:998: VisibleDeprecationWarning: The signature of <bound method smail_gen._rvs of <skypy.galaxy.redshift.smail_gen object at 0x116eb4a90>> does not contain a "size" keyword.  Such signatures are deprecated.
    np.VisibleDeprecationWarning)

.tox/test-scipy15/lib/python3.7/site-packages/skypy/pipeline/tests/test_skypy.py::test_skypy
  .tox/test-scipy15/lib/python3.7/site-packages/skypy/pipeline/tests/test_skypy.py:35: ResourceWarning: unclosed file <_io.TextIOWrapper name='.tox/test-scipy15/lib/python3.7/site-packages/skypy/pipeline/tests/data/cosmology_config.yaml' mode='r' encoding='UTF-8'>
    assert skypy.main(['--config', filename]) == 0

.tox/test-scipy15/lib/python3.7/site-packages/skypy/power_spectrum/_camb.py::skypy.power_spectrum._camb.camb
  .tox/test-scipy15/lib/python3.7/site-packages/_pytest/doctest.py:401: ResourceWarning: unclosed file <_io.FileIO name='.tox/test-scipy15/lib/python3.7/site-packages/skypy/pipeline/tests/data/empty_config.yaml' mode='rb' closefd=True>
    all_skipped = all(x.options.get(doctest.SKIP, False) for x in test.examples)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=========================== short test summary info ============================
FAILED ../../.tox/test-scipy15/lib/python3.7/site-packages/skypy/galaxy/ellipticity.py::skypy.galaxy.ellipticity.beta_ellipticity_gen
FAILED ../../.tox/test-scipy15/lib/python3.7/site-packages/skypy/galaxy/tests/test_ellipticity.py::test_beta_ellipticity
FAILED ../../.tox/test-scipy15/lib/python3.7/site-packages/skypy/galaxy/tests/test_ellipticity.py::test_ryden04
================== 3 failed, 53 passed, 33 warnings in 4.33s ===================
ERROR: InvocationError for command .tox/test-scipy15/bin/pytest --pyargs skypy docs (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   test-scipy15: commands failed
```

Two of the three errors stem from changes to `scipy.stats`, and the last one is a little mysterious.

**Comment by ntessore** [comment]
Closed by #199 and #202.
