### ISSUE TITLE
Readthedocs cannot build camb

### ISSUE THREAD

**Issue by rrjbca** [skypyproject/skypy#220]
**Describe the bug**
The readthedocs build for v0.2rc1 fails because it does not have a gfortran compiler to build camb.

Extract from https://readthedocs.org/projects/skypy/builds/11455118/

```
Building wheels for collected packages: skypy, pyyaml, camb, sphinx-gallery, mpmath
  Building wheel for skypy (PEP 517): started
  Building wheel for skypy (PEP 517): finished with status 'done'
  Created wheel for skypy: filename=skypy-0.2rc1-py3-none-any.whl size=69506 sha256=17bb870c4a4578bb007207ef4f4a48578e44d24d5fee94da5c11e31b804e70c6
  Stored in directory: /tmp/pip-ephem-wheel-cache-poq09r30/wheels/78/e7/42/80f43f3d2849bd7c92fe213f06820a0789a4cead717843454e
  Building wheel for pyyaml (setup.py): started
  Building wheel for pyyaml (setup.py): finished with status 'done'
  Created wheel for pyyaml: filename=PyYAML-5.3.1-cp37-cp37m-linux_x86_64.whl size=44619 sha256=5d7737272f16a4718d92a5e1a05a68be78f5f1dd6fd3f0c0d137d33365a75c83
  Stored in directory: /tmp/pip-ephem-wheel-cache-poq09r30/wheels/5e/03/1e/e1e954795d6f35dfc7b637fe2277bff021303bd9570ecea653
  Building wheel for camb (setup.py): started
  Building wheel for camb (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /home/docs/checkouts/readthedocs.org/user_builds/skypy/envs/v0.2.x/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bq5yuirc/camb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bq5yuirc/camb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-3heu_963
       cwd: /tmp/pip-install-bq5yuirc/camb/
  Complete output (35 lines):
  running bdist_wheel
  running build
  running build_py
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-bq5yuirc/camb/setup.py", line 308, in <module>
      python_requires='>=3.6'
    File "/home/docs/checkouts/readthedocs.org/user_builds/skypy/envs/v0.2.x/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/docs/checkouts/readthedocs.org/user_builds/skypy/envs/v0.2.x/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-bq5yuirc/camb/setup.py", line 233, in run
      make_library(False)
    File "/tmp/pip-install-bq5yuirc/camb/setup.py", line 111, in make_library
      ok, gfortran_version = _compile.check_gfortran(msg=not _compile.is_windows)
    File "/tmp/pip-install-bq5yuirc/camb/camb/_compilers.py", line 73, in check_gfortran
      version, gfortran_version, 'https://camb.readthedocs.io/en/latest/fortran_compilers.html'))
  Exception: You need ifort or gfortran 6 or higher to compile (found: None).
  See https://camb.readthedocs.io/en/latest/fortran_compilers.html
  ----------------------------------------
  ERROR: Failed building wheel for camb
  Running setup.py clean for camb
  Building wheel for sphinx-gallery (setup.py): started
  Building wheel for sphinx-gallery (setup.py): finished with status 'done'
  Created wheel for sphinx-gallery: filename=sphinx_gallery-0.7.0-py3-none-any.whl size=113990 sha256=fca135a8c4c98e14f7dbf5140232eb9134b1e28fb184b8cce92ae169bff388e5
  Stored in directory: /tmp/pip-ephem-wheel-cache-poq09r30/wheels/29/9c/f2/b89fbd3b8d077989a1c59392a083430027a419687a8a2087b0
  Building wheel for mpmath (setup.py): started
  Building wheel for mpmath (setup.py): finished with status 'done'
  Created wheel for mpmath: filename=mpmath-1.1.0-py3-none-any.whl size=532239 sha256=c775fe69c86ff81a8d916da9cc535fdd4fffe663447f925d540f16e78d517117
  Stored in directory: /tmp/pip-ephem-wheel-cache-poq09r30/wheels/e2/46/78/e78f76c356bca9277368f1f97a31b37a8cb937176d9511af31
Successfully built skypy pyyaml sphinx-gallery mpmath
Failed to build camb
```

**Comment by NickSam121** [comment]
Hello,

I am facing a similar problem. Although I have downloaded all the latest version of python3.9, gcc on my MacBook Pro Big Sur, I still get the following:


(base) nicksam121@nicksam121s-mbp CAMB-1.2.0 % python setup.py make

running make
Traceback (most recent call last):
  File "/Users/nicksam121/Desktop/CAMB-1.2.0/setup.py", line 269, in <module>
    setup(name=os.getenv('CAMB_PACKAGE_NAME', 'camb'),
  File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/nicksam121/Desktop/CAMB-1.2.0/setup.py", line 221, in run
    make_library(False)
  File "/Users/nicksam121/Desktop/CAMB-1.2.0/setup.py", line 111, in make_library
    ok, gfortran_version = _compile.check_gfortran(msg=not _compile.is_windows)
  File "/Users/nicksam121/Desktop/CAMB-1.2.0/camb/_compilers.py", line 71, in check_gfortran
    raise Exception(
Exception: You need ifort or gfortran 6 or higher to compile (found: None).
See https://camb.readthedocs.io/en/latest/fortran_compilers.html


Also,
(base) nicksam121@nicksam121s-mbp CAMB-1.2.0 % import camb
zsh: command not found: import

Any ideas?

Regards,
Nick

**Comment by NickSam121** [comment]
My alias are the 

alias python="/usr/local/bin/python3.9" 

alias gcc="/usr/local/bin/gcc-10"

alias cpp="/usr/local/bin/gpp-10"

alias g++="/usr/local/bin/g++-10"

alias c++="/usr/local/bin/c++-10"

**Comment by ntessore** [comment]
@NickSam121 You are very, very much in the wrong place. But your actual error is

    You need ifort or gfortran 6 or higher to compile (found: None).
    See https://camb.readthedocs.io/en/latest/fortran_compilers.html

If you look at the mentioned webpage (which is where you should go for CAMB support) it will tell you to download the linked Fortran compiler. There is no reason to reply here.
